### ISSUE TITLE
Some characters dont load

### ISSUE THREAD

**Issue by Cydget** [shinyquagsire23/SaltySD#1] opened 2016-01-31 02:27 UTC
Peach is one of these characters for me n3ds. While others on o3ds said that fox and falcon dont load.
When you select one and try to start a match, the game straight up crashes.

**Comment by shinyquagsire23** [comment] 2016-01-31 02:42
Recreated on my end, odd that it would do that. I'm working on cleaning up some things in terms of memory, it might remedy that issue. If it's an allocation issue, then that would be tricky to fix.

**Comment by shinyquagsire23** [comment] 2016-02-01 00:24
Fixed as of bf8e07b5cd283d0ee75d23873e3b691c13910e90, it was caused by concurrent threads accessing the shared .bss region at the same time.

**Closed by shinyquagsire23** 2016-02-01 00:24 UTC
