### ISSUE TITLE
Game Crashing w/ Kirby & Bayonetta

### ISSUE THREAD

**Issue by Shishiwaka** [shinyquagsire23/SaltySD#10] opened 2016-03-16 03:22 UTC
So whenever Kirby Inhales Bayo, the game crashes. 
Have tested it on solo and in group mode. 
Have not had a chance of testing it with other characters. 
Here's my setup for reference: A9LH w/ ARN on O3DS on 10.7 with a physical copy.

**Comment by Cydget** [comment] 2016-03-17 21:11
I already made a report of this crash. Its under the Kirby Hat issue

**Comment by shinyquagsire23** [comment] 2016-03-20 01:57
Yeah duplicate of #5

**Closed by shinyquagsire23** 2016-03-20 01:57 UTC
