### ISSUE TITLE
Classic mode doesnt work

### ISSUE THREAD

**Issue by Cydget** [shinyquagsire23/SaltySD#2] opened 2016-01-31 02:28 UTC
When you attempt to start classic mode, the game crashes. Tested on o3ds and n3ds

**Comment by shinyquagsire23** [comment] 2016-02-01 00:24
Confirmed and then fixed as of bf8e07b5cd283d0ee75d23873e3b691c13910e90, it was caused by concurrent threads accessing the shared .bss region at the same time.

**Closed by shinyquagsire23** 2016-02-01 00:24 UTC
